name: Interval
author: Ian Kaplan
description: "A lean Jupyter notebook runner for simple and fast Github Workflows"
inputs:
  notebook:
    description: "Notebook to run"
    required: true
  requirements:
    description: "String of requirements to pass into container e.x. 'package1==1.0.0 package2==1.1.0'"
    required: false
  parameters:
    description: "Papermill will inject the yaml string [-y] [value] into the #parameters cell"
    required: false
  parameterFile:
    description: "Option for passing in a parameters.yml file"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.parameters }}
    - ${{ inputs.requirements }}
    - ${{ inputs.notebook }}
    - ${{ secrets.IntervalSecret }}
branding:
  icon: 'clock'
  color: 'yellow'