name: hybrid-interval
author: Ian Kaplan
description: "A lean Jupyter notebook runner for simple and fast Github Workflows"
inputs:
  notebook:
    description: "Notebook to run on Interval"
    required: true
  requirements:
    description: "String of requirements to pass into container e.x. 'package1==1.0.0 package2==1.1.0'"
    required: false
  parameters:
    description: "Papermill will inject the yaml string [-y] [value] into the #parameters cell"
    required: false
  parameterFile:
    description: "Option for passing in a parameters.yml file"
    required: false
  secret:
    description: "Gives Notebook access to secrets in execution environment. 
      Use expression syntax (e.g. ${{ secret.IntervalSecret }}) to mask value"
    required: false
  outputNotebook:
    description: "Specifies output notebook filepath e.x 's3://outputs/interval.ipynb'"
    required: false
    default: output.ipynb
  hasDate:
    description: "Adds date to ouptut filename e.x. 's3://outputs/interval-2020-01-01.ipynb' "
    required: false
    default: "false"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.parameters }}
    - ${{ inputs.parameterFile }}
    - ${{ inputs.requirements }}
    - ${{ inputs.notebook }}
    - ${{ inputs.secret }}
    - ${{ inputs.outputNotebook }}
    - ${{ inputs.hasDate }}
branding:
  icon: 'clock'
  color: 'yellow'
